{{- if and .Values.monitoring.enabled .Values.monitoring.postgresExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}-postgres-exporter
  labels:
    {{- include "postgresql.exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql.exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql.exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres-exporter
        image: "{{ .Values.monitoring.postgresExporter.image.repository }}:{{ .Values.monitoring.postgresExporter.image.tag }}"
        imagePullPolicy: {{ .Values.monitoring.postgresExporter.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: 9187
          protocol: TCP
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-postgres-exporter
              key: datasource
        {{- if .Values.monitoring.postgresExporter.queries }}
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: /etc/postgres-exporter/queries.yaml
        volumeMounts:
        - name: queries
          mountPath: /etc/postgres-exporter/queries.yaml
          subPath: queries.yaml
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          {{- toYaml .Values.monitoring.postgresExporter.resources | nindent 10 }}
      {{- if .Values.monitoring.postgresExporter.queries }}
      volumes:
      - name: queries
        configMap:
          name: {{ include "postgresql.fullname" . }}-postgres-exporter-queries
      {{- end }}
{{- end }}

