{{- if and .Values.kube-prometheus-stack.grafana.enabled .Values.features.grafana }}
{{- if .Values.grafanaIngress.tls.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitor.fullname" . }}-grafana
  namespace: {{ include "monitor.namespace" . }}
  labels:
    {{- include "monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
  annotations:
    {{- include "monitor.grafana.ingress.annotations" . | nindent 4 }}
    {{- include "monitor.annotations" . | nindent 4 }}
spec:
  {{- if .Values.grafanaIngress.ingressClassName }}
  ingressClassName: {{ .Values.grafanaIngress.ingressClassName }}
  {{- end }}
  tls:
    - hosts:
        {{- include "monitor.grafana.ingress.tlsHosts" . | nindent 8 }}
      secretName: {{ include "monitor.grafana.ingress.tlsSecret" . }}
  rules:
    - host: {{ include "monitor.grafana.ingress.host" . }}
      http:
        paths:
          - path: {{ .Values.grafanaIngress.path }}
            pathType: {{ .Values.grafanaIngress.pathType }}
            backend:
              service:
                name: {{ include "monitor.grafana.serviceName" . }}
                port:
                  number: {{ .Values.grafanaIngress.servicePort }}
{{- end }}
{{- end }}

