{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-pgbouncer-config
  labels:
    {{- include "postgresql.pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |
    [databases]
    {{ .Values.postgresql.database }} = host={{ include "postgresql.fullname" . }}-postgresql port={{ .Values.postgresql.service.port }} dbname={{ .Values.postgresql.database }}
    
    [pgbouncer]
    pool_mode = {{ .Values.pgbouncer.poolMode }}
    listen_addr = 0.0.0.0
    listen_port = 5432
    auth_type = plain
    auth_file = /etc/pgbouncer/userlist.txt
    admin_users = {{ if .Values.pgbouncer.adminUsers }}{{ join "," .Values.pgbouncer.adminUsers }}{{ else }}{{ .Values.postgresql.username }}{{ end }}
    stats_users = {{ if .Values.pgbouncer.statsUsers }}{{ join "," .Values.pgbouncer.statsUsers }}{{ else }}{{ .Values.postgresql.username }}{{ end }}
    
    max_client_conn = {{ .Values.pgbouncer.maxClientConn }}
    default_pool_size = {{ .Values.pgbouncer.defaultPoolSize }}
    min_pool_size = {{ .Values.pgbouncer.minPoolSize }}
    reserve_pool_size = {{ .Values.pgbouncer.reservePoolSize }}
    reserve_pool_timeout = {{ .Values.pgbouncer.reservePoolTimeout }}
    max_db_connections = {{ .Values.pgbouncer.maxDBConnections }}
    max_user_connections = {{ .Values.pgbouncer.maxUserConnections }}
    
    server_idle_timeout = 600
    server_connect_timeout = 15
    server_login_retry = 15
    query_timeout = 0
    query_wait_timeout = 120
    client_idle_timeout = 0
    client_login_timeout = 60
    autodb_idle_timeout = 3600
    
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    ignore_startup_parameters = extra_float_digits
    
    application_name_add_host = 1
    
    listen_backlog = 128
    sbuf_loopcnt = 5
    tcp_defer_accept = 0
    tcp_socket_buffer = 0
    tcp_keepalive = 1
    tcp_keepcnt = 3
    tcp_keepidle = 600
    tcp_keepintvl = 30
{{- end }}

