{{- if and .Values.backend.enabled .Values.ingress.enabled .Values.ingress.backend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app-js.backend.name" . }}
  labels:
    {{- include "app-js.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-headers@kubernetescrd
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.backend.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.backend.host }}
    secretName: {{ include "app-js.backend.name" . }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.ingress.backend.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "app-js.backend.name" . }}
            port:
              number: {{ .Values.services.backend.port }}
{{- end }}

